name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.*'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: true

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1.3
        
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64

      - name: Build GUI
        env:
          QTFRAMEWORK_BYPASS_LICENSE_CHECK: 1
        run: cmake --build build --config Release --target gui
        
      - name: Build tests
        env:
          QTFRAMEWORK_BYPASS_LICENSE_CHECK: 1
        run: cmake --build build --config Release
        
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure -C Release

      - name: Create portable package
        run: cmake --build build --target package_zip --config Release

      - name: Find and verify ZIP file
        run: |
          $BUILD_VERSION = (git log -1 --format=%cd --date=format:%Y%m%d)
          $SHORT_SHA = (git rev-parse --short HEAD)
          $PACKAGE_NAME = "trappable-$BUILD_VERSION-$SHORT_SHA-windows.zip"
          $ZIP_PATH = "build\$PACKAGE_NAME"
          
          if (Test-Path $ZIP_PATH) {
            Write-Host "✓ ZIP file verified: $ZIP_PATH"
            echo "PACKAGE_NAME=$PACKAGE_NAME" >> $env:GITHUB_ENV
            echo "BUILD_VERSION=$BUILD_VERSION" >> $env:GITHUB_ENV
          } else {
            Write-Host "✗ ZIP file not found: $ZIP_PATH"
            Write-Host "Available files in build directory:"
            Get-ChildItem build -Name
            exit 1
          }

      - name: Upload to Dropbox
        if: github.ref == 'refs/heads/main' && success()
        uses: Lewuathe/dropbox-github-action@v1.0.3
        with:
          dropbox-app-key: ${{ secrets.DROPBOX_APP_KEY }}
          dropbox-app-secret: ${{ secrets.DROPBOX_APP_SECRET }}
          dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source-path: build/${{ env.PACKAGE_NAME }}
          target-path: /builds/${{ env.BUILD_VERSION }}/${{ env.PACKAGE_NAME }}
          write-mode: add